/*
 * The Curule UI kit's tokens: the values every surface shares, written once.
 *
 * The site, the account pages and the console are three stylesheets for three kinds of page, and they had begun to say the
 * same things in different numbers: three shadows, two greens, four radii. The kit is the part that must be the same
 * everywhere: the colour roles, the elevation ladder, the radii, the tracking and the motion. It is generated into each
 * stylesheet between two fence comments, so no surface can drift from it by being edited by hand:
 *
 *   node scripts/build-brand.mjs           rewrites the blocks (and brand/kit.css, the same tokens on their own)
 *   node scripts/build-brand.mjs --check   exits 1 if a block differs (npm run brand:check)
 *
 * What is not here: the brand's seven colours (brand/tokens.css; this file starts from them, and a test keeps them equal),
 * the console's status colours and role colours (they were derived to a contrast target and are pinned by
 * tests/build/console-palette.test.ts; the kit's status colours are the same values), and any component. A component
 * is built from these in the stylesheet that owns it.
 *
 * Names: every token here is `--k-*`. A stylesheet's own names (`--bg`, `--panel`, `--accent` ...) may alias them.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

export const BEGIN = "/* @kit:tokens begin (generated by scripts/kit-tokens.mjs: edit the script and run `npm run brand:build`, not this block) */";
export const END = "/* @kit:tokens end */";

/** Per-theme values. The light set is the default of the site and the account pages; the dark set is the console's default. */
export const THEMES = {
  light: {
    // surfaces
    bg: "#fbfaf8", // the brand's paper
    surface: "#ffffff", // the brand's panel: a card, a dialog, a field
    "surface-2": "#f7f5f1", // a step down from a card: a table head, a hovered row
    sunken: "#f1eee8", // a well: a track, a code block, a segmented control's trough
    // lines
    line: "#e4e0d9", // the brand's line: decoration, never the only edge of a control
    "line-strong": "#d3cdc2",
    "line-control": "#837d72", // >= 3:1 on surface and on sunken: the edge of a field
    // text
    ink: "#1c1b1a", // the brand's ink
    "ink-2": "#3d3a36", // a lead paragraph, a table's first column
    muted: "#5d5a55", // the brand's muted text
    // the one blue
    accent: "#2b5fd9", // the brand's blue: a fill, a ring, a large glyph
    "accent-hover": "#2655ca",
    "accent-press": "#1f47a8",
    "accent-ink": "#2150bd", // the blue as text on surface or on accent-soft
    "accent-soft": "#eaf0fc",
    "on-accent": "#ffffff",
    // status (the console's values; each clears 4.5:1 as text at a 14% self-tint over sunken)
    ok: "#0a6b49",
    warn: "#7c5808",
    bad: "#a53349",
    info: "#24676e",
    // elevation: 1 sits on a page, 2 is a card that can be pressed, 3 floats (a menu), 4 is a dialog, 5 is the hero's device
    "shadow-1": "0 1px 2px rgba(28, 27, 26, .05)",
    "shadow-2": "0 1px 2px rgba(28, 27, 26, .06), 0 4px 12px -2px rgba(28, 27, 26, .08)",
    "shadow-3": "0 2px 4px rgba(28, 27, 26, .05), 0 12px 28px -6px rgba(28, 27, 26, .14)",
    "shadow-4": "0 4px 8px rgba(28, 27, 26, .06), 0 24px 56px -12px rgba(28, 27, 26, .22)",
    "shadow-5": "0 8px 16px rgba(28, 27, 26, .06), 0 40px 96px -24px rgba(28, 27, 26, .34)",
    hl: "inset 0 1px 0 rgba(255, 255, 255, .72)", // the lit top edge of a raised control
    scrim: "rgba(28, 27, 26, .42)",
  },
  dark: {
    bg: "#131211",
    surface: "#1b1a18",
    "surface-2": "#22211e",
    sunken: "#0e0d0c",
    line: "#302e2a",
    "line-strong": "#45423b",
    "line-control": "#7a746a",
    ink: "#efece6",
    "ink-2": "#d6d2c9",
    muted: "#aaa59c",
    accent: "#7ba0ff",
    "accent-hover": "#9db8ff",
    "accent-press": "#b6caff",
    "accent-ink": "#9db8ff",
    "accent-soft": "#1a2236",
    "on-accent": "#0e1220",
    ok: "#43d6a0",
    warn: "#f0b429",
    bad: "#f07381",
    info: "#56b6c2",
    "shadow-1": "0 1px 2px rgba(0, 0, 0, .4)",
    "shadow-2": "0 1px 2px rgba(0, 0, 0, .45), 0 4px 12px -2px rgba(0, 0, 0, .4)",
    "shadow-3": "0 2px 4px rgba(0, 0, 0, .45), 0 12px 28px -6px rgba(0, 0, 0, .55)",
    "shadow-4": "0 4px 8px rgba(0, 0, 0, .5), 0 24px 56px -12px rgba(0, 0, 0, .7)",
    "shadow-5": "0 8px 16px rgba(0, 0, 0, .5), 0 40px 96px -24px rgba(0, 0, 0, .85)",
    hl: "inset 0 1px 0 rgba(255, 255, 255, .07)",
    scrim: "rgba(8, 7, 6, .62)",
  },
};

/** The same in both themes. */
export const SHARED = {
  // the focus ring: a soft halo; the hard 2px outline is still drawn by :focus-visible, this is for fields that grow one
  ring: "0 0 0 3px color-mix(in srgb, var(--k-accent) 30%, transparent)",
  // shape
  "r-xs": "4px",
  "r-sm": "6px",
  "r-md": "10px",
  "r-lg": "14px",
  "r-xl": "20px",
  "r-pill": "999px",
  // type: the system's own fonts (nothing is downloaded), and the tracking that goes with each size of text
  font: 'system-ui, -apple-system, "Segoe UI", Roboto, sans-serif',
  mono: 'ui-monospace, SFMono-Regular, Menlo, Consolas, monospace',
  "track-display": "-.04em", // the hero
  "track-title": "-.022em", // a heading
  "track-tight": "-.011em", // a card title, a lead
  "track-caps": ".08em", // a small label in capitals
  // motion
  ease: "cubic-bezier(.2, .7, .2, 1)", // things arriving
  "ease-io": "cubic-bezier(.4, 0, .2, 1)", // things moving
  "dur-1": "120ms", // a hover, a press
  "dur-2": "180ms", // a menu, a tooltip
  "dur-3": "300ms", // a panel, a reveal
  // atmosphere: a wash of the blue from above, and the ledger's ruled lines (32px, the rhythm of a row)
  glow: "radial-gradient(60% 70% at 50% 0%, color-mix(in srgb, var(--k-accent) 13%, transparent), transparent 72%)",
  rule: "repeating-linear-gradient(to bottom, transparent 0, transparent 31px, color-mix(in srgb, var(--k-line) 80%, transparent) 31px, color-mix(in srgb, var(--k-line) 80%, transparent) 32px)",
};

const decl = (set, indent) => Object.entries(set).map(([k, v]) => `${indent}--k-${k}: ${v};`).join("\n");

/**
 * The block for one kind of stylesheet.
 *   "system"   the site and the account pages: light, and the visitor's dark setting switches it (no toggle)
 *   "console"  the console: dark, and `[data-theme="light"]` switches it (the console follows the system until chosen)
 */
export function kitBlock(mode) {
  if (mode === "system") {
    return `${BEGIN}
:root {
${decl(SHARED, "  ")}
${decl(THEMES.light, "  ")}
}
@media (prefers-color-scheme: dark) {
  :root {
${decl(THEMES.dark, "    ")}
  }
}
${END}`;
  }
  if (mode === "console") {
    return `${BEGIN}
:root {
${decl(SHARED, "  ")}
${decl(THEMES.dark, "  ")}
}
[data-theme="light"] {
${decl(THEMES.light, "  ")}
}
${END}`;
  }
  throw new Error(`unknown kit block mode: ${mode}`);
}

/** Every stylesheet that carries the block, and which kind it is. */
export const TARGETS = [
  { file: "site/assets/site.css", mode: "system" },
  { file: "apps/cloud-server/pages/assets/app.css", mode: "system" },
  { file: "apps/mesh-dashboard/src/styles.css", mode: "console" },
];

/** `css` with the text between the fences replaced by `block`. Throws when the fences are missing: a stylesheet must opt in. */
export function inject(css, block, name = "stylesheet") {
  const a = css.indexOf(BEGIN);
  const b = css.indexOf(END);
  if (a < 0 || b < a) throw new Error(`${name} has no ${BEGIN.slice(0, 30)}... fence pair: add the two comments where the kit's tokens go`);
  return css.slice(0, a) + block + css.slice(b + END.length);
}

/** `{ file, want, have }` for every target. `have` is what is on disk, `want` what the kit says it should be. */
export function kitState(base = root) {
  return TARGETS.map(({ file, mode }) => {
    const have = readFileSync(join(base, file), "utf8");
    return { file, have, want: inject(have, kitBlock(mode), file) };
  });
}

/** brand/kit.css: the system-mode block on its own, for a person (or a page) that wants the tokens and nothing else. */
export function kitFile() {
  return `/* Curule UI kit tokens. Generated by scripts/kit-tokens.mjs: change the script, not this file.
   The site, the account pages and the console carry the same values in their own stylesheets. */
${kitBlock("system")}
`;
}

/** Writes every block. Returns the files that changed. */
export function writeKit(base = root) {
  const changed = [];
  for (const s of kitState(base)) {
    if (s.have !== s.want) {
      writeFileSync(join(base, s.file), s.want);
      changed.push(s.file);
    }
  }
  return changed;
}
